"""Shared audit columns, used by both the Bronze (`raw_*`) and Gold (`dim_*`/`fct_*`) layers.

Purpose
-------
docs/07_DATABASE_SCHEMA.md requires every table to carry `created_at`,
`updated_at`, `pipeline_version`, and `source` ("Audit Fields... supports
lineage, debugging, reproducibility"), and separately mandates UUID primary
keys ("Decision 002"). Every model in this project follows the identical
pattern for both, so it lives once here as a pair of mixins rather than
being retyped on each model — the risk with retyping being that one model
quietly drifts (e.g. a forgotten `nullable=False`) and nobody notices until
a bad row gets through.

Two mixins, not one, because Bronze and Gold name their primary keys
differently:

- **Bronze** (`AuditMixin`, used by `app/models/raw/*.py`) includes a
  generic `id` column — every raw table's primary key is just "the row's
  id," since Bronze is an internal staging layer this project doesn't
  expose a naming convention for.
- **Gold** (`GoldAuditMixin`, used by `app/models/gold/*.py`) deliberately
  does *not* include a primary key — docs/07_DATABASE_SCHEMA.md's "Naming
  Convention" section mandates entity-specific primary key names for the
  star schema (`driver_id`, `constructor_id`, `season_id`, ...), which each
  Gold model declares itself.

`id`/`created_at`/`updated_at` on Bronze rows are populated by
`apps/ingestion`'s loaders (see `apps/ingestion/utils/ids.py` for why `id`
is a deterministic, not random, UUID). On Gold rows they're populated by
`apps/ingestion`'s transformer (`apps/ingestion/transformers/bronze_to_gold.py`)
— `source` there is always `"transform"`, distinguishing a derived Gold row
from a directly-collected Bronze one.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, Uuid, func
from sqlalchemy.orm import Mapped, mapped_column


class AuditMixin:
    """Adds `id`, `source`, `pipeline_version`, `created_at`, `updated_at`
    to a Bronze (`raw_*`) model, in that column order.

    `id` is expected to be *supplied* by the caller (deterministically, via
    `apps/ingestion/utils/ids.py::generate_id`) rather than randomly
    generated by the database — there is deliberately no
    `default=uuid.uuid4` here, since that would break idempotent
    re-ingestion (see that module's docstring).
    """

    id: Mapped[uuid.UUID] = mapped_column(Uuid(), primary_key=True)
    source: Mapped[str] = mapped_column(nullable=False)
    pipeline_version: Mapped[str] = mapped_column(nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class GoldAuditMixin:
    """Adds `source`, `pipeline_version`, `created_at`, `updated_at` to a
    Gold (`dim_*`/`fct_*`) model — everything `AuditMixin` adds except
    `id`, since each Gold model declares its own entity-specific primary
    key column instead (see module docstring).
    """

    source: Mapped[str] = mapped_column(nullable=False)
    pipeline_version: Mapped[str] = mapped_column(nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
