"""create gold dimension and fact tables

Revision ID: 8d4a909547da
Revises:
Create Date: 2026-07-19 21:05:21.736115

Creates the Gold layer's dimensions and facts (docs/07_DATABASE_SCHEMA.md),
hand-written to mirror `app/models/gold/*.py` exactly, for the same reason
`alembic/versions/bc6a4663b61a_...py` (the raw/Bronze migration) is
hand-written rather than autogenerated: no live database is available in
this environment to diff against. Runs against the analytics database via
`alembic -c alembic_gold.ini upgrade head`.

Table creation order matters here (unlike the raw/Bronze migration, which
has no foreign keys between its tables at all): `dim_constructor`,
`dim_circuit`, and `dim_weather` have no dependencies and come first;
`dim_driver` depends on `dim_constructor`; `dim_season` has no
dependencies; `dim_session` depends on all three of `dim_season`,
`dim_weather`, and `dim_circuit`; and the fact tables
(`fct_results`/`fct_laps`/`fct_pitstop`) depend on both `dim_driver` and
`dim_session`.
"""

from collections.abc import Sequence
from typing import Any

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8d4a909547da"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _gold_audit_columns() -> list[sa.Column[Any]]:
    """The four audit columns every Gold table shares (no primary key here —
    unlike Bronze's `AuditMixin`, each Gold table declares its own
    entity-specific PK column; see `app/models/mixins.py::GoldAuditMixin`).
    """
    return [
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("pipeline_version", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
    ]


def upgrade() -> None:
    op.create_table(
        "dim_season",
        sa.Column("season_id", sa.Uuid(), nullable=False),
        *_gold_audit_columns(),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("race_count", sa.Integer(), nullable=False),
        sa.Column("sprint_count", sa.Integer(), nullable=True),
        sa.Column("champion_driver", sa.String(), nullable=True),
        sa.Column("champion_constructor", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("season_id"),
    )
    op.create_index("ix_dim_season_year", "dim_season", ["year"], unique=True)

    op.create_table(
        "dim_constructor",
        sa.Column("constructor_id", sa.Uuid(), nullable=False),
        *_gold_audit_columns(),
        sa.Column("team_name", sa.String(), nullable=False),
        sa.Column("base_country", sa.String(), nullable=True),
        sa.Column("team_principal", sa.String(), nullable=True),
        sa.Column("power_unit", sa.String(), nullable=True),
        sa.Column("primary_color", sa.String(), nullable=True),
        sa.Column("secondary_color", sa.String(), nullable=True),
        sa.Column("logo", sa.String(), nullable=True),
        sa.Column("car_image", sa.String(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("constructor_id"),
    )

    op.create_table(
        "dim_circuit",
        sa.Column("circuit_id", sa.Uuid(), nullable=False),
        *_gold_audit_columns(),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("length", sa.Float(), nullable=True),
        sa.Column("corners", sa.Integer(), nullable=True),
        sa.Column("drs_zones", sa.Integer(), nullable=True),
        sa.Column("lap_record", sa.String(), nullable=True),
        sa.Column("clockwise", sa.Boolean(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("svg_track", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("circuit_id"),
    )

    op.create_table(
        "dim_weather",
        sa.Column("weather_id", sa.Uuid(), nullable=False),
        *_gold_audit_columns(),
        sa.Column("air_temperature", sa.Float(), nullable=True),
        sa.Column("track_temperature", sa.Float(), nullable=True),
        sa.Column("humidity", sa.Float(), nullable=True),
        sa.Column("wind_speed", sa.Float(), nullable=True),
        sa.Column("wind_direction", sa.Float(), nullable=True),
        sa.Column("rainfall", sa.Boolean(), nullable=True),
        sa.Column("pressure", sa.Float(), nullable=True),
        sa.Column("track_status", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("weather_id"),
    )

    op.create_table(
        "dim_driver",
        sa.Column("driver_id", sa.Uuid(), nullable=False),
        *_gold_audit_columns(),
        sa.Column("driver_number", sa.Integer(), nullable=True),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("abbreviation", sa.String(), nullable=True),
        sa.Column("nationality", sa.String(), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("team_id", sa.Uuid(), nullable=True),
        sa.Column("rookie_season", sa.Integer(), nullable=True),
        sa.Column("world_titles", sa.Integer(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("driver_id"),
        sa.ForeignKeyConstraint(["team_id"], ["dim_constructor.constructor_id"]),
    )

    op.create_table(
        "dim_session",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        *_gold_audit_columns(),
        sa.Column("season_id", sa.Uuid(), nullable=False),
        sa.Column("round_number", sa.Integer(), nullable=False),
        sa.Column("race_name", sa.String(), nullable=True),
        sa.Column("session_type", sa.String(), nullable=False),
        sa.Column("date", sa.String(), nullable=True),
        sa.Column("weather_id", sa.Uuid(), nullable=True),
        sa.Column("circuit_id", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("session_id"),
        sa.ForeignKeyConstraint(["season_id"], ["dim_season.season_id"]),
        sa.ForeignKeyConstraint(["weather_id"], ["dim_weather.weather_id"]),
        sa.ForeignKeyConstraint(["circuit_id"], ["dim_circuit.circuit_id"]),
        sa.UniqueConstraint(
            "season_id", "round_number", "session_type", name="uq_dim_session_natural_key"
        ),
    )
    op.create_index("ix_dim_session_season_id", "dim_session", ["season_id"])

    op.create_table(
        "fct_results",
        sa.Column("result_id", sa.Uuid(), nullable=False),
        *_gold_audit_columns(),
        sa.Column("driver_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("grid_position", sa.Float(), nullable=True),
        sa.Column("finish_position", sa.Float(), nullable=True),
        sa.Column("points", sa.Float(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("fastest_lap", sa.Boolean(), nullable=True),
        sa.Column("laps_completed", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("result_id"),
        sa.ForeignKeyConstraint(["driver_id"], ["dim_driver.driver_id"]),
        sa.ForeignKeyConstraint(["session_id"], ["dim_session.session_id"]),
        sa.UniqueConstraint("session_id", "driver_id", name="uq_fct_results_natural_key"),
    )
    op.create_index("ix_fct_results_driver_id", "fct_results", ["driver_id"])
    op.create_index("ix_fct_results_session_id", "fct_results", ["session_id"])

    op.create_table(
        "fct_laps",
        sa.Column("lap_id", sa.Uuid(), nullable=False),
        *_gold_audit_columns(),
        sa.Column("driver_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("lap_number", sa.Float(), nullable=False),
        sa.Column("lap_time", sa.Float(), nullable=True),
        sa.Column("sector_1", sa.Float(), nullable=True),
        sa.Column("sector_2", sa.Float(), nullable=True),
        sa.Column("sector_3", sa.Float(), nullable=True),
        sa.Column("compound", sa.String(), nullable=True),
        sa.Column("tyre_life", sa.Float(), nullable=True),
        sa.Column("position", sa.Float(), nullable=True),
        sa.Column("speed_trap", sa.Float(), nullable=True),
        sa.Column("drs", sa.Boolean(), nullable=True),
        sa.Column("pit_in", sa.Boolean(), nullable=True),
        sa.Column("pit_out", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("lap_id"),
        sa.ForeignKeyConstraint(["driver_id"], ["dim_driver.driver_id"]),
        sa.ForeignKeyConstraint(["session_id"], ["dim_session.session_id"]),
        sa.UniqueConstraint(
            "session_id", "driver_id", "lap_number", name="uq_fct_laps_natural_key"
        ),
    )
    op.create_index("ix_fct_laps_driver_id", "fct_laps", ["driver_id"])
    op.create_index("ix_fct_laps_session_id", "fct_laps", ["session_id"])

    op.create_table(
        "fct_pitstop",
        sa.Column("pitstop_id", sa.Uuid(), nullable=False),
        *_gold_audit_columns(),
        sa.Column("driver_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("lap", sa.Float(), nullable=False),
        sa.Column("pit_duration", sa.Float(), nullable=True),
        sa.Column("stop_number", sa.Integer(), nullable=True),
        sa.Column("compound_before", sa.String(), nullable=True),
        sa.Column("compound_after", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("pitstop_id"),
        sa.ForeignKeyConstraint(["driver_id"], ["dim_driver.driver_id"]),
        sa.ForeignKeyConstraint(["session_id"], ["dim_session.session_id"]),
        sa.UniqueConstraint("session_id", "driver_id", "lap", name="uq_fct_pitstop_natural_key"),
    )
    op.create_index("ix_fct_pitstop_driver_id", "fct_pitstop", ["driver_id"])
    op.create_index("ix_fct_pitstop_session_id", "fct_pitstop", ["session_id"])


def downgrade() -> None:
    # Reverse dependency order.
    op.drop_table("fct_pitstop")
    op.drop_table("fct_laps")
    op.drop_table("fct_results")
    op.drop_table("dim_session")
    op.drop_table("dim_driver")
    op.drop_table("dim_weather")
    op.drop_table("dim_circuit")
    op.drop_table("dim_constructor")
    op.drop_table("dim_season")
