"""Shared columns for every Bronze-layer (`raw_*`) model.

Purpose
-------
docs/07_DATABASE_SCHEMA.md requires every table to carry `created_at`,
`updated_at`, `pipeline_version`, and `source` ("Audit Fields... supports
lineage, debugging, reproducibility"), and separately mandates UUID primary
keys ("Decision 002"). Every `raw_*` model in this package follows the
identical pattern for both, so it lives once here as a mixin rather than
being retyped on each model — the risk with retyping being that one model
quietly drifts (e.g. a forgotten `nullable=False`) and nobody notices until
a bad row gets through.

Inputs
------
None — this is a set of column declarations, not a function.

Outputs
-------
`id`: a UUID primary key. Every row's `id` is expected to be *supplied* by
the caller (typically `apps/ingestion`'s loader, via
`utils.ids.generate_id`) rather than randomly generated by the database —
deterministic ids are what make re-ingesting an already-loaded season an
idempotent upsert instead of a duplicate insert (see
`apps/ingestion/utils/ids.py`). There is deliberately no
`default=uuid.uuid4` here.

`source`: which upstream produced this row (`"fastf1"` or `"jolpica"`).
Bronze tables never merge across sources (see `app/models/raw/__init__.py`),
so this column is part of several tables' natural-key uniqueness
constraints, not just descriptive metadata.

`pipeline_version`: which version of the ingestion pipeline produced this
row — lets a future data-quality investigation ask "did this look wrong
before or after pipeline version X shipped?" without guessing from
`created_at` timestamps alone.

`created_at` / `updated_at`: standard audit timestamps. `updated_at` uses
`onupdate=func.now()`, which SQLAlchemy evaluates and includes in the
`UPDATE` statement itself (not a database-native trigger), so this behaves
identically whether the target database is PostgreSQL (production) or
SQLite (tests) — no dialect-specific trigger DDL is needed.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, Uuid, func
from sqlalchemy.orm import Mapped, mapped_column


class AuditMixin:
    """Adds `id`, `source`, `pipeline_version`, `created_at`, `updated_at`
    to any model that inherits it, in that column order."""

    id: Mapped[uuid.UUID] = mapped_column(Uuid(), primary_key=True)
    source: Mapped[str] = mapped_column(nullable=False)
    pipeline_version: Mapped[str] = mapped_column(nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
